### ISSUE TITLE
moveItemsToTrash Api error TypeError: result is not iterable (cannot read property undefined)

### ISSUE THREAD

**Issue by bartczar** [xob0t/Google-Photos-Toolkit#20]
Continuing my trashing quest ...

Source read complete
Found items: 12466
Items to process: 12466
Moving 12466 items to trash
Processing 500 items
Processing 500 items
Processing 500 items
moveItemsToTrash Api error TypeError: result is not iterable (cannot read property undefined)
Processing 500 items
Processing 500 items
Processing 500 items
moveItemsToTrash Api error TypeError: Cannot read properties of null (reading '0')
TypeError: Cannot read properties of null (reading '0')
moveItemsToTrash Api error SyntaxError: "undefined" is not valid JSON

**Comment by xob0t** [comment]
try setting API OPERATION BATCH SIZE to a smaller number
