### ISSUE TITLE
Cannot delete folder created with "move to new folder"

### ISSUE THREAD

**Issue by bartczar** [xob0t/Google-Photos-Toolkit#21]
I have used the function to move photos to new folder.

Then I have removed all photos from the folder.

And now I cannot delete this folder from Google GUI. The request just hangs and never finishes with no error.

**Comment by xob0t** [comment]
google photo issue, not related to GPTK

**Comment by bartczar** [comment]
How come it's unrelated. If I create an album directly from the GUI I have never experienced problems deleting it. 

The issue is that if I create an album with GPTK THEN I cannot delete it with GUI and GPTK does not have the option to delete albums.

**Comment by xob0t** [comment]
albums created with gptk and webui are identical, if google photo cannot delete an album, that is a google photo issue

I see two possibilities: 
- just this album just happens to be bugged
- this is a broader issue and any album will fail to delete

You can try clearing cookies, if it does not help, i'd bet it will sort itself out in a day or two.
