### ISSUE TITLE
Script Not Seeing All Items

### ISSUE THREAD

**Issue by phoenixxx-1** [xob0t/Google-Photos-Toolkit#28]
Hello,

I have migrated away from Google Photos after Google changed the storage quotas for Pixel Phones.  I am using this toolkit to delete everything in Google Photos (my word, Google have made this difficult!).

The userscript processed a chunk of my photos (I believe around 23k) but there are many photos remaining (~40GB, all using "saver storage").

When I select move to trash on the library page with no filters set I receive the following:

No media items on the page!
Source read complete
Found items: 0
No items to process.

I am running this from the photos.google.com homepage and am running Chrome 127.0.6533.100 on MacOS 14.6 and Tampermonkey 5.2.3.

Any help would be appreciated.

Thanks!

**Comment by xob0t** [comment]
should be fixed in v2.4.4
