### ISSUE TITLE
Restore from trash fails with an error

### ISSUE THREAD

**Issue by ndv400** [xob0t/Google-Photos-Toolkit#30]
Source read complete
Found items: 28079
Items to process: 28079
Restoring 28079 items from trash
Processing 500 items
Processing 500 items
Processing 500 items
Processing 500 items
Processing 500 items
restoreFromTrash Api error TypeError: Cannot read properties of null (reading '0')
TypeError: Cannot read properties of null (reading '0')
restoreFromTrash Api error TypeError: Cannot read properties of null (reading '0')
restoreFromTrash Api error TypeError: Cannot read properties of null (reading '0')

**Comment by xob0t** [comment]
Try lowering `Api Operation Batch Size` to 50 or less.

**Comment by ndv400** [comment]
OK, I will. 
Is this also related to Api Operation Batch Size?
Processing 500 items
Processing 500 items
moveItemsToTrash Api error SyntaxError: "undefined" is not valid JSON
SyntaxError: "undefined" is not valid JSON

**Comment by xob0t** [comment]
May be. There is a bug in the Google Photos api, in my experience setting lower batch size fixes it.

**Comment by xob0t** [comment]
@ndv400
Did it help?

**Comment by ndv400** [comment]
Sorry for the very late reply.
It was still erroring out at 50: 
Source read complete
Found items: 33989
Items to process: 33989
Restoring 33989 items from trash
Processing 50 items
Processing 50 items
Processing 50 items
Processing 50 items
Processing 50 items
Processing 50 items
restoreFromTrash Api error TypeError: Cannot read properties of null (reading '0')
TypeError: Cannot read properties of null (reading '0')
restoreFromTrash Api error TypeError: Cannot read properties of null (reading '0')
restoreFromTrash Api error TypeError: Cannot read properties of null (reading '0')
Same goes for 30:
Processing 30 items
restoreFromTrash Api error TypeError: Cannot read properties of null (reading '0')
TypeError: Cannot read properties of null (reading '0')
However, when I put it to 10 and tried on another computer with a different IP address it started working for a while, and then failed again:
Processing 10 items
Processing 10 items
Processing 10 items
Processing 10 items
Processing 10 items
restoreFromTrash Api error TypeError: Cannot read properties of null (reading '0')
TypeError: Cannot read properties of null (reading '0')
restoreFromTrash Api error TypeError: Cannot read properties of null (reading '0')
restoreFromTrash Api error TypeError: Cannot read properties of null (reading '0')

**Comment by xob0t** [comment]
@ndv400 Does restoring from the trash using the UI work? Try selecting a few hundred items and restoring them manually.
