### ISSUE TITLE
Feature Request: Support an array of file names in "Filename" filter

### ISSUE THREAD

**Issue by just-inlewis** [xob0t/Google-Photos-Toolkit#36]
My OG Pixel device often leaves behind photos that have "failed" to upload after "Freeing up space". Often times, these files are in fact present in Google Photos. I can verify these items are present or not by using the "Filename" filter but this is tedious to do one by one. It would be awesome if I could provide an array of filenames to query or even a CSV file containing the files to query.

**Comment by xob0t** [comment]
Hi.
You can match multiple filenames with regex.
Here is an example
```regex
^name1\.jpg$|^name2\.jpg$|^name3\.jpg$
```
Pro tip:
The best way to check if a file is uploaded is by its hash.
Generate a file hash with bash, or use a different powershell command for windows.
```bash
sha1sum "/path/to/file" | xxd -r -p | base64
```
Go to the https://photos.google.com/, open the browser console, insert and run the code to get remote matches by hash

```js
const hashes = ["eMxa/4hnrPkqEEAdexfUuTybcas=", "2jmj7l5rSw0yVb/vlWAYkK/YBwk="]
matches = await gptkApi.getRemoteMatchesByHash(hashes)
console.log(matches)
```
