### ISSUE TITLE
Filter Live Photos (Feature idea)

### ISSUE THREAD

**Issue by branislav-remen** [xob0t/Google-Photos-Toolkit#4]
Another useful filter would be option to select only Live Photos.
Live Photos taken by iPhone contains at least 2 files - image (jpg) and video (mov). 
Because of the video it takes more space which could be cleaned using Toolkit.
Other use case - I would download all live photos and merged them to the one video (for example memories from vacation, etc...)

**Comment by xob0t** [comment]
Leaving it here for my future self for when i have the time to look into it
https://github.com/photoprism/photoprism/files/4048676/iPhone.X.Live.Photo.Samples.zip

**Comment by xob0t** [comment]
Those 2 files are just that, two separate files, the only common traits seems to be filename and date, so to identify all live photos in a GP library, we would have to scan it whole, then look for img - video pairs with identical dates/filenames.
Not an elegant solution, but it would work.

**Comment by pzemo** [comment]
Live photos have separate icon at the top, maybe it can be searched without downloading? And for saving space it could be great tool to automate slight edit of every live photo what deletes the live part.

**Comment by xob0t** [comment]
> Live photos have separate icon at the top, maybe it can be searched without downloading? And for saving space it could be great tool to automate slight edit of every live photo what deletes the live part.

I've uploaded [those samples](https://github.com/xob0t/Google-Photos-Toolkit/issues/4#issuecomment-2070945722) to my GP, and I don't see any special icons in the web version.

**Comment by pzemo** [comment]
try this sample, one iphone's HEIC file combinig movie and picture, and screenshot with live photo icon

**Comment by xob0t** [comment]
@pzemo the heic file is just 2.5MB, does not seem to include video
[Apple Live Photo file format](https://stackoverflow.com/questions/32508375/apple-live-photo-file-format)

**Comment by pzemo** [comment]
Hard to share it, its 5.05MB https://photos.app.goo.gl/XXfHS9twRbjoHYhd7

**Comment by xob0t** [comment]
that did it, thanks!

I don't know why, but just uploading video and audio files does not make GP recognize them as a single live photo.
When i download your shared photo, it dls as zip with jpg and mov inside, and if reupload them, GP shows them as two separate media items.

I think i've found how to identify live photos, but seems like deleting the live part would not be trivial, as GP stores them as a single object and the only way to do so seems to be to modify it in some way with the "edit" tool, as GP removes the "live" part on edit.
Maybe it would be possible to "edit" them without any actual changes to the image, idk

**Comment by xob0t** [comment]
added live photo filter in #15
