### ISSUE TITLE
Add Title based on filename, size, ...

### ISSUE THREAD

**Issue by PetrVys** [xob0t/Google-Photos-Toolkit#40]
First thanks for amazing tool. I just wish Google would publish API like this instead of limiting the official one year by year...

It would be very useful for me to automatically set Title of my pictures (e.g. call following endpoint):
```
[[["AQNOFd","[null,\"{Title goes here}\",\"{Photo ID goes here}\"]",null,"generic"]]]
```

My idea is that I'd make a CSV file (or JSON, ...) with values e.g. "Filename, file size, title", paste it into window in your program and Google-Photos-Toolkit would check the existing titles and where it does not match, it will set it accordingly.

Since setting of title is now not possible during upload, this would enable me to set titles based on EXIF tags, directories holding the photos uploaded to GPhoto etc.

On a related note: Do you have any idea how to generate Google photos dedup_id based on image data? It'd be best to use that for this task; and it can obviously be done (the iOS and android apps clearly do it as they're able to avoid uploading duplicities), but it is a black magic for me so far.

**Comment by PetrVys** [comment]
Ok, so by pure luck I found out how to create the dedup_id locally - it is SHA1 hash of the image data encoded in BASE64. Following file has dedup_id of HgmapQ2FNj41qb5VwDCH4ulneP8 in GPhotos:

```
>certutil -hashfile IMG_3203.PNG SHA1
SHA1 hash of IMG_3203.PNG:
1e099aa50d85363e35a9be55c03087e2e96778ff
>echo 1e099aa50d85363e35a9be55c03087e2e96778ff > IMG_3203.SHA
>certutil -decodehex IMG_3203.SHA IMG_3203.BIN
>certutil -encodehex -f IMG_3203.bin IMG_3203.b64 0x40000001
>type IMG_3203.b64
HgmapQ2FNj41qb5VwDCH4ulneP8=
```

**Comment by xob0t** [comment]
@PetrVys Hi!
I see you figured out dedup keys yourself, here is my comment with some more info you could find useful https://github.com/xob0t/Google-Photos-Toolkit/issues/36#issuecomment-2424657275

What you're calling title is probably a description.
You can set them using the api like so
```js
await gptkApi.setItemDescription("dedup_key", "desctiption_text")
```

**Comment by PetrVys** [comment]
Thanks, I last time looked deeply at the code about half a year ago, and I see you’ve improved it a lot. This will indeed do :-)
