### ISSUE TITLE
getAlbums only fetches albums created by user

### ISSUE THREAD

**Issue by happy-turtle** [xob0t/Google-Photos-Toolkit#42]
I wanted to move all images that are not in any album. I ran into problems, because getAlbums was only fetching albums that I created myself. Shared albums that I uploaded to, but others created, were missing. After trying to view all albums with photos' UI, I inspected the request and changed

https://github.com/xob0t/Google-Photos-Toolkit/blob/136e01bd2c9ecc4fc9722e21e1cbf74cd858e9a2/src/api/api.js#L234

to `[pageId, null, null, null, 1, null, null, pageSize, [2], 5]`. That did the trick for me and I was then getting all albums as I expected.

**Comment by xob0t** [comment]
Thanks, fixed in v2.5.4
