### ISSUE TITLE
"Refresh albums" returns no albums (bug)

### ISSUE THREAD

**Issue by branislav-remen** [xob0t/Google-Photos-Toolkit#5]
Hello,

**IS:**
- I have albums in GPhotos, but GPT shows "No Albums"

**SHOULD:**
- Show list of albums.

**Notes:**
Yesterday it worked. List of albums was visible. I've created 2-3 albums using GPT. Today I removed these albums and refershed list of the Albums. No Albums are visible now.
I don't see errors in console. Network calls ends with OK code (Responses make no sense to me).
I've tried to clear storage/cookies, reload userscript/browser, log-in/out. 
Could you try to reproduce it? Thank you.

**LOG:** 
```
Cached Albums Restored
Found 53 items
Found 61 items
Found 77 items
No items found!
Albums Refreshed
```

<img width="1512" alt="image" src="https://github.com/xob0t/Google-Photos-Toolkit/assets/43781862/2411b90c-ecd4-496c-8d37-987677630781">

**Comment by branislav-remen** [comment]
Source of the problem is in this function:
```
    async getAllItems(apiMethod, ...args) {
      const items = [];
      let nextPageId = null;
      do {
        if (!this.core.isProcessRunning) return;
        const page = await apiMethod.call(this.api, ...args, nextPageId);
        if (!page?.items) {
          log('No items found!', 'error');
          return [];
        }
        items.push(...page.items);
        log(`Found ${page.items.length} items`);
        nextPageId = page.nextPageId;
      } while (nextPageId);
      return items;
    }
```

For some (for me unknown) reason `page` contains `nextPageId`. But the next api call returns null.
I've placed this piece of code right after API call to quickfix it.


```
    if (page === null) {
          nextPageId = null;
          break;
        }
```

**Comment by xob0t** [comment]
Not having this issue, although, I don't have that many albums.
You can try it on another GP account.

GP lists items in pages, if a page has a nextPageId, then the next page exists and has items.
In that case the page has the nextPageId, but when script reads the next page, it unexpectedly has no items, so it fails and returns 0 items.

Can be 'fixed' with returning found items it case of an error.
`return [];`  -> `return items;`
But that may introduce a scenario, when if something goes wrong (say, while reading the library), script prints an error, then just continues to process the incomplete data.
I'd be good to ask a user what to do, maybe an alert asking if it should ignore the error.

Or it could be just a rare GP bug, and it'll sort itself out :)

**Comment by xob0t** [comment]
i've added an "ignore errors" checkbox, do you still have this error, can you test if that fixes it?
Its in the advanced settings
https://github.com/xob0t/Google-Photos-Toolkit/raw/ignore-errors/google_photos_toolkit.user.js

**Comment by waltersdmh** [comment]
I've had the same issue as @branislav-remen. After attempting a quick fix about 80% of the albums load.
Sadly the Ignore Errors flag does not help.

**Comment by xob0t** [comment]
Looks like it depends on the page size and album count.
By default albums page size is 100, same as used by GP itself.
On my main GP account I have 53 albums, no issues getting them all with page size 100.
If I change page size to 10, It gets all of them, but the last page will have nextPageId even though it should not.
Setting page size to 9, and it all works fine as it was.
Creating an empty album so the total is 54 and setting page size to 10 also works.
Having 54 albums and setting page to 4 gets all but 1 of them, then errors on the empty page.

I'll remove `if (!page?.items)` check in the next update, meanwhile, try creating an empty album or two, maybe it'll fix it for you.

**Comment by waltersdmh** [comment]
thanks for resolving this! The refresh albums function no longer errors out for me. 

I am however still having a problem where not all albums are found. I have a feeling that google returns a blank page and a next pageID for some reason.

**Comment by xob0t** [comment]
thanks for the feedback, I'll take note of hidden albums
