### ISSUE TITLE
Not finding "Not owned" video

### ISSUE THREAD

**Issue by shuraka** [xob0t/Google-Photos-Toolkit#7]
When trying to find "Any" or even only "Video" media while selecting "Not owned" it returns 0 objects. It works well with photos.
v2.0
![image](https://github.com/xob0t/Google-Photos-Toolkit/assets/25867050/bf5ab204-f30f-4f22-acd4-acf13c0e47a2)

**Comment by xob0t** [comment]
fixed in v2.3.2
