### ISSUE TITLE
No files appear at all in GPTK

### ISSUE THREAD

**Issue by samandiriel** [xob0t/Google-Photos-Toolkit#9]
- Using Chromium Version 125.0.6422.112 (Official Build) snap (64-bit) on Ubuntu
- Latest version of tampermonkey, developer mode turned on
- Nothing obvious appears in console.
- Searching also produces no results

![Selection_247](https://github.com/xob0t/Google-Photos-Toolkit/assets/3135396/e54e2f08-dacb-4157-b7b8-e82ff13394bc)

**Comment by xob0t** [comment]
Are you sure you're following instructions in the readme?
Set the filter, then choose the action. After choosing action it must at least log start time, but your log is totally empty.

**Comment by samandiriel** [comment]
> Are you sure you're following instructions in the readme? Set the filter, then choose the action. After choosing action it must at least log start time, but your log is totally empty.

Ah, I understand better now.  I didn't realize from the README that there wasn't some kind of feedback such as displaying number of items found by a filter before committing the action selection.  Now that I know and have tried that, I can see the process.  Thank you!
